=== jeztrem/AngularWord/src/app/data/schema/section.schema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "array",
    "title": "The Root Schema",
    "items": {
      "$id": "#/items",
      "type": "object",
      "title": "The Items Schema",
      "required": [
        "id",
        "header",
        "book",
        "chapter",
        "start",
        "finish",
        "introduction",
        "summary"
      ],
      "properties": {
        "id": {
          "$id": "#/items/properties/id",
          "type": "integer",
          "title": "The Id Schema",
          "default": 0,
          "examples": [
            0
          ]
        },
        "header": {
          "$id": "#/items/properties/header",
          "type": "string",
          "title": "The Header Schema",
          "default": "",
          "examples": [
            "Introduction"
          ],
          "pattern": "^(.*)$"
        },
        "book": {
          "$id": "#/items/properties/book",
          "type": "string",
          "title": "The Book Schema",
          "default": "",
          "examples": [
            "James"
          ],
          "pattern": "^(.*)$"
        },
        "chapter": {
          "$id": "#/items/properties/chapter",
          "type": "integer",
          "title": "The Chapter Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "start": {
          "$id": "#/items/properties/start",
          "type": "integer",
          "title": "The Start Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "finish": {
          "$id": "#/items/properties/finish",
          "type": "integer",
          "title": "The Finish Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "introduction": {
          "$id": "#/items/properties/introduction",
          "type": "array",
          "title": "The Introduction Schema",
          "items": {
            "$id": "#/items/properties/introduction/items",
            "type": "string",
            "title": "The Items Schema",
            "default": "",
            "examples": [
              "About James",
              "James was the younger brother of Jesus.",
              "Wealth of knowledge, may sound like his older brother sometimes.",
              "Cross reference into the Gospels and Jesus Teachings",
              "Book of James thought to be written 40 AD.",
              "James is mentioned in Jerusalem Council: Act 15.",
              "James was martyred 62 AD."
            ],
            "pattern": "^(.*)$"
          }
        },
        "summary": {
          "$id": "#/items/properties/summary",
          "type": "array",
          "title": "The Summary Schema",
          "items": {
            "$id": "#/items/properties/summary/items",
            "type": "string",
            "title": "The Items Schema",
            "default": "",
            "examples": [
              "Blueprint for how to think, act, plan as a Christian.",
              "Book can be crushingly hard. Reading it can make me feel like a failure.",
              "Important to dwell on the gospel: Now that I have been redeemed, how do I live?",
              "Now that I have heard the word of God, how do I do it?",
              "Spirits power: Remind ourselves the reason why we can attempt to be this way.",
              "James isn't telling us how to get saved, he is telling us how to live now that we are saved.",
              "Try and mix in some encouragement from other his and other books."
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    }
  }

=== jeztrem/AngularWord/src/app/data/section/obadiah.json
[
    {
        "id": 0,
        "header": "Introduction",
        "book": "Obadiah",
        "chapter": 1,
        "start": 1,
        "finish": 1,
        "introduction": [
            "*** Slide: Outline (Open verse one for references.)",
            "Jacob and Esau: Up until Jacob Leaves.",
            "*** Slide: Family Tree ",
            "------Twins fighting in the womb.",
            "------Jacob (One who grabs the heel, or cheat)",
            "------Isaac loved Esau, Rebekah loved Jacob",
            "------Jacob buys Esau's birthright with some red stew.",
            "------Rebekah and Jacob collude to steal Esau's blessing from Isaac.",
            "------Esau plans to kill Jacob, Rebekah and Jacob plan an escape to her brother Laban.",
            "*** Slide: Map of Nations of Terah.",
            "*** Slide: Family Tree ",
            "Jacob and Esau: When Jacob returns",
            "------Jacob returns some 20 years later.",
            "------Jacob prepares to meet his brother.",
            "------Esau welcomes him with open arms, Jacob tricks him one more time.",
            "------Esau returns to the land of Seir, or Edom",
            "Some 400+ years pass.",
            "------Jacob becomes Israel, Esau becomes Edom.",
            "------Israelites want to pass through Edom. Edom says no.",
            "*** Slide: Path of Israelites",
            "*** Slide: Bozrah",
            "*** Slide: Judah-vs-Edom",
            "Another 800+ years pass.",
            "------Judah is overcome by Babylon, Edom stands by watching, cheering, waiting."
        ],
        "summary": [
            "There is a lot history here.",
            "*** Slide: Bozrah",
            "Isaiah: And the streams of Edom shall be turned into pitch, and her soil into sulfur; her land shall become burning pitch.",
            "Jeremiah: Many of the same prophecies of Obadiah: Edom shall become a horror. Everyone who passes by it will be horrified and will hiss because of all its disasters. 18As when Sodom and Gomorrah and their neighboring cities were overthrown, says the Lord, no man shall dwell there, no man shall sojourn in her.",
            "Ezekiel: As you rejoiced over the inheritance of the house of Israel, because it was desolate, so I will deal with you; you shall be desolate, Mount Seir, and all Edom, all of it. Then they will know that I am the Lord.",
            "Joel: Egypt shall become a desolation and Edom a desolate wilderness, for the violence done to the people of Judah, because they have shed innocent blood in their land.",
            "Amos: So I will send a fire upon Teman, and it shall devour the strongholds of Bozrah.”",
            "God's anger with them centered on their pride and their gloating over the fall Judah and Israel.",
            "Micah: Yet I have loved Jacob but Esau I have hated. (God's Sovereign Choice: Romans 9)"
        ]
    },
    {
        "id": 1,
        "header": "Edom's Pride",
        "book": "Obadiah",
        "chapter": 1,
        "start": 1,
        "finish": 9,
        "introduction": [
            "*** Slide: Cliff dwellings. verses 4, 6, 9",
            "1). Attack would be difficult.",
            "2). Economic success from being at a crossing of trade routes.",
            "3). Apparently known for wise men and military might.",
            "4). Treaties with the surrounding nations.",
            "Reminds me a little of CH.",
            "Safe, and Secure and confident they can keep themselves that way."
        ],
        "summary": [
            "*** references in 9",
            "See that God objected to their self-confidence, saying their pride had deceived them.",
            "God swept away safety and security, despite there confidence. (Home, treasures, treaties, wise and mighty men.)",
            "Obvious parallels to us here in the US.",
            "How can we not be deceived by our own pride?",
            "How can we not make the same mistake as Edom.",
            "1). No self-confidence, (Proverbs 3, Joshua 1, Psalm 121)",
            "==== Not in some of my ways, all of my ways.",
            "==== Being strong and courageous, because I know the Lord is on my side.",
            "2). Grave mistake to believe in our efforts result in our safety and security. (James 4, Luke 12)",
            "==== My natural tendency is to seek protection from the world through natural means. (good job, safe neighborhood, secure passwords,...",
            "==== My mistake is that I see these as more than just tools, and don't acknowledge God for my safety.",
            "==== If I think I am somehow clever and make my posessions impregnable, I am making Edom's mistake, not acknowledging perfect giver.",
            "==== Edom being stripped bare Jer 49 'I have uncovered his hiding places' => wherever you might be hiding your valuables: they are vunerable",
            "==== Like the man in James 4, or the Rich fool in Luke 12.",
            "==== I'm not saying we should test God by not locking our doors, but grab hold of the truth that he is our safety and security.",
            "3). It is for our own good. (James 4:6, 1 Peter)",
            "==== Don't want to be put in a position of being opposed by God.",
            "==== Grades of a student. (Acknowledge Him)",
            "==== Good at work. (Acknowledge Him)",
            "==== Don't take credit for accomplishments",
            "Transition: Edom's transgression is Pride."
        ]
    },
    {
        "id": 2,
        "header": "Edom's Gloating",
        "book": "Obadiah",
        "chapter": 1,
        "start": 10,
        "finish": 14,
        "introduction": [
            "Transition: Edom's transgression: Gloating over Israel's demise.",
            "Might ask why is this wrong?",
            "Israel and Edom were for the most part enemies.",
            "Picture layed out in scripture: By God's choice, Jacob was the choosen twin, loved and blessed. But the nation didn't obey God, and they were punished for it.",
            "Open verse 11, 14."
        ],
        "summary": [
            "Lay it bare, Lay it Bare was not the response that God desired from Edom.",
            "A better response would have been love your neighbor as yourself: not to gloat, to show mercy and pity on their brother nation, helping those fleeing the violence.",
            "How can we apply this today?",
            "One could say this was a unique situation.",
            "Same picture is layed out in scripture for us as followers of Christ, we are choosen, loved and blessed.",
            "When I see other Christians stumble, how do I respond?",
            "What are my secret thoughts I can gloat:",
            "==== Someone I don't know personally: I knew it, they were just pretending, what a hypocrite.",
            "==== Someone I know personally: If they would just do things the right way: read their Bible and pray, they wouldn't have this issue.",
            "In my heart I'm making the same mistake as Edom, gloating and not showing mercy.",
            "Have to be careful with my secret thoughts, that I show mercy.",
            "Its natural to ask the questions: Why did this happen to them?, or What can I learn so that doesn't happen to me? ",
            "Although it is natural to ask these questions, but I'm not sure that is always the best or even necessary.",
            "Late 90s, Teacher HIV",
            "Jesus addresses this issue in Luke 13.",
            "Far more important to repent, then the need to know why something bad happened to someone."
        ]
    },
    {
        "id": 3,
        "header": "The Day",
        "book": "Obadiah",
        "chapter": 1,
        "start": 15,
        "finish": 16,
        "introduction": [
            "Good reason to repent is that we all stumble. And all nations will be judged.",
            "Open verse 15"
        ],
        "summary": [
            "**** Day of the Lord: Slide.",
            "==== For the last several weeks and the coming weeks we hear from God that the nations are not doing well.",
            "==== Punishment is not pretty.",
            "==== Isaiah 34:2",
            "==== Bad Dog",
            "No good news."
        ]
    },
    {
        "id": 4,
        "header": "Coming Kingdom",
        "book": "Obadiah",
        "chapter": 1,
        "start": 17,
        "finish": 21,
        "introduction": [
            "The good news: no judgement for us.",
            "Open verse 17"
        ],
        "summary": [
            "Conclusion",
            "Special Relationship between Jacob and Esau.",
            "How pride deceives us.",
            "Gloating over others misfortune",
            "Through Christ we have escaped the coming judgement.",
            "==== We can learn about what God wants and doesn't want from us."
        ]
    }
]

=== jeztrem/AngularWord/src/app/data/section/blank.json
[
    {
        "id": 0,
        "header": "Introduction",
        "book": "Obadiah",
        "chapter": 1,
        "start": 1,
        "finish": 1,
        "introduction": [
           
        ],
        "summary": [
        ]
    },
    {
        "id": 1,
        "header": "Finding Joy in Trials",
        "book": "Obadiah",
        "chapter": 1,
        "start": 2,
        "finish": 4,
        "introduction": [
        ],
        "summary": [
        ]
    },
    {
        "id": 2,
        "header": "Asking for Wisdom",
        "book": "Obadiah",
        "chapter": 1,
        "start": 5,
        "finish": 8,
        "introduction": [
        ],
        "summary": [
        ]
    }
]
